### ISSUE TITLE
provide a working, minimal setup to build on

### ISSUE THREAD

**Issue by jangalinski** [AxonIQ/axon-server-plugin-api#7]
I cannot get a plugin running using this documentation.

I tried a minimal setup here: <https://github.com/holixon/axon-server-plugin-example>

I would expect it to either fail (throws exception) or somehow log anything, but nothing happens although the plugin jar can be uploaded and activated.

I would love to work together with you to move my example  repo to your space and continue building a"hello world" setup that logs to the same log the server uses so the different interceptors at least have some output.

**Comment by MGathier** [comment]
I ran the example you created using the docker compose file and it did not install, because of the IllegalStateException. This error is returned in the CLI command and also logged in the server logs. 
When I try to upload it again it does install, but remains in status "Installed", starting it does not change its status. Unfortunately, at this point nothing is reported or logged, so we should improve on this. 
And yes, we want to provide one or more sample plugins to get plugin developers started.

**Comment by jangalinski** [comment]
Thanks for trying. Yes, now I see it too, must have been some confusion on my side.

**Comment by lfgcampos** [comment]
Hi @jangalinski, as already shared here is an example for the plugins.
https://github.com/AxonIQ/axon-server-plugin-example

There are still enhancements to be made like add one example for each type of interceptor but we can keep this kind of request on that repo.
Having said that, I am going to close this issue if you don't mind.

**Comment by jangalinski** [comment]
I don't mind at all. Thank you very much @lfgcampos  ... the example helped me to overcome the initial problems (and thus led to more advanced problems :-))
